### ISSUE TITLE
Vagrant Repeatedly Reports Connection Refused

### ISSUE THREAD

**Issue by chrissphinx** [hashicorp/vagrant#10655]
### Vagrant version
Vagrant 2.2.3

### VMware Fusion version
Professional Version 11.0.2 (10952296)

### Host operating system
macOS Mojave 10.14.3

### Guest operating system
64-bit Ubuntu 16.04 LTS (bento/ubuntu-16.04)

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
end
```

### Debug output
https://gist.github.com/chrissphinx/a3e8125f2869489a7f17bbcc7f879741

### Expected behavior
SSH Connection is Established

### Actual behavior
SSH Connection Fails

### Steps to reproduce
1. `vagrant up`

### Remarks
I was honestly just using `vagrant` yesterday and it was working fine. I even was able to `vagrant ssh` into a machine a bit earlier this evening, but the `/vagrant` folder was not mounted as expected.

If I open vmWare Fusion after the failure, I can log into the VM normally with the default user and password.

https://gist.github.com/chrissphinx/a3e8125f2869489a7f17bbcc7f879741#file-vagrant-log-L1413

I don't quite understand what's happening here, but I have nothing running on 2222 that could be collided with (I had just restarted my machine and ran nothing but this), yet it is trying to repair it?

Also, in my repeatedly flailing of destroying and continually bringing the VM up, sometimes it will then complain:

```
Vagrant failed to apply the requested port forward. The following
error message was generated while attempting to apply the port
forward rule:

  Port forward conflict on host port 2222

Please resolve any problems reported in the error message above and
try again.
```

or even that an error occurred when trying to prune unused ports. So, I it seems something is really wrong here ...

**Comment by briancain** [comment]
@chrissphinx - When you log into the machine, does it have networking? (i.e. can you ping things, does it have an IP...) Is sshd running? Can you ssh into the machine without using Vagrant at all? Thanks!

**Comment by chrissphinx** [comment]
At the point it got to here:
```
Bringing machine 'default' up with 'vmware_desktop' provider...
==> default: Cloning VMware VM: 'bento/ubuntu-16.04'. This can take some time...
==> default: Checking if box 'bento/ubuntu-16.04' version '201812.27.0' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for the VM to receive an address...
==> default: Forwarding ports...
    default: -- 22 => 2222
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection refused. Retrying...
```

I opened up vmWare Fusion application, logged in with default Vagrant user and password, got the IP from `ifconfig` and then SSH'd into it from a terminal session. No issues at all.

I could also ping, dig and curl Google.

**Comment by chrissphinx** [comment]
Also I see this behavior after trying to poke at it further:
```
$ vagrant provision
$ vagrant provision
$ vagrant suspend
==> default: Suspending the VMware VM...
$ vagrant up
Bringing machine 'default' up with 'vmware_desktop' provider...
==> default: Checking if box 'bento/ubuntu-16.04' version '201812.27.0' is up to date...
==> default: Verifying vmnet devices are healthy...
Vagrant encountered an error while attempting to prune unused
port forward entries:

  Failed to delete port forward
$ vagrant resume
==> default: Checking if box 'bento/ubuntu-16.04' version '201812.27.0' is up to date...
==> default: Verifying vmnet devices are healthy...
Vagrant encountered an error while attempting to prune unused
port forward entries:

  Failed to delete port forward
```

But I can easily resume it from within vmWare Fusion and again SSH to it without issue.

Sorry if I'm being verbose here...

**Comment by briancain** [comment]
@chrissphinx - did you try ssh'ing with key auth, or did you use a username and password?

**Comment by chrisroberts** [comment]
@chrissphinx There is also an update available for the vagrant-vmware-utility which addresses some port forwarding issues. Upgrading that may resolve the issues you are encountering.

**Comment by chrissphinx** [comment]
@chrisroberts is `vagrant-vmware-desktop (2.0.3, global)` not the most up-to-date version? I ran `vagrant plugin update vagrant-vmware-desktop` and it said plugins are up-to-date.

**Comment by chrissphinx** [comment]
@briancain now it's doing this:
```
$ vagrant reload
==> default: Attempting graceful shutdown of VM...
==> default: Checking if box 'bento/ubuntu-16.04' version '201812.27.0' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for the VM to receive an address...
==> default: Forwarding ports...
    default: -- 22 => 2222
Vagrant failed to apply the requested port forward. The following
error message was generated while attempting to apply the port
forward rule:

  Port forward conflict on host port 2222

Please resolve any problems reported in the error message above and
try again.
$ vagrant ssh
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-131-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

0 packages can be updated.
0 updates are security updates.


Last login: Tue Feb 12 01:08:38 2019 from 192.168.120.1
vagrant@vagrant:~$
```

but since it doesn't come up properly, `/vagrant` is not mounted properly still.

Key is in place and authorized though:

```
vagrant@vagrant:~$ cat ~/.ssh/authorized_keys
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeL3hnH9wlequkmVoqZfhhCHI3oR/SHvKhQHiNBj1sEi/RKwo+MmDfnzBgV3D0bovoaBuGwyZ54JbQ+odKTMfLITydrlBieZ+Zxl/lDHRW6dbSBhWY8UpXoqe8+D9+ez11fEvK6CLJllHQxf8RNs3InS8cbAk6RlZp7UyE3cinpBg0LdebGkhByuBhI2ff51cvI4BWs9rtn4Gzp0EgPnfziFaiG4xPfT6E7fWKSY0FJWsKzYrptMoA5v9hxjEOiPo4+zM5Uj3r+gJDx5vrzo8A8B7hAeuSewvKckn+ylJz7WU8fk1nqjX/D3KqBp+e0y0PSm68E5PbfxtisabMh/jF vagrant
vagrant@vagrant:~$ exit
logout
Connection to 192.168.120.166 closed.
$ ssh-keygen -y -f .vagrant/machines/default/vmware_desktop/private_key
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCeL3hnH9wlequkmVoqZfhhCHI3oR/SHvKhQHiNBj1sEi/RKwo+MmDfnzBgV3D0bovoaBuGwyZ54JbQ+odKTMfLITydrlBieZ+Zxl/lDHRW6dbSBhWY8UpXoqe8+D9+ez11fEvK6CLJllHQxf8RNs3InS8cbAk6RlZp7UyE3cinpBg0LdebGkhByuBhI2ff51cvI4BWs9rtn4Gzp0EgPnfziFaiG4xPfT6E7fWKSY0FJWsKzYrptMoA5v9hxjEOiPo4+zM5Uj3r+gJDx5vrzo8A8B7hAeuSewvKckn+ylJz7WU8fk1nqjX/D3KqBp+e0y0PSm68E5PbfxtisabMh/jF
```

**Comment by briancain** [comment]
@chrissphinx - The latest vmware utility looks to be `1.0.7`. If you can upgrade that, it should fix your port forwarding issue. https://www.vagrantup.com/vmware/downloads.html Thanks!

**Comment by chrissphinx** [comment]
@briancain after installation and a restart, behavior is exactly the same.

Where can I confirm the version of this component? It is not listed in `vagrant plugin list`...

**Comment by chrissphinx** [comment]
I've reinstalled `vagrant`, `vagrant-vmware-utility` and `vagrant-vmware-desktop` plugin (after using `vagrant plugin expunge --reinstall`) and the problem persists.

I'm really at a loss here. Port 2222 is simply not in use by the host machine so I don't know why it is complaining about this.

**Comment by chrissphinx** [comment]
I will note that using vbox 6.0 provider works just fine, no issues. I'd really like to not have to have both vm softwares on my machine as vmware is already licensed through my university but it seems my issue is isolated to me... 😞

**Comment by chrisroberts** [comment]
There is a chance that a stray port forward was left in the VMware configuration and is not being seen to be removed. See this comment for more information: https://github.com/hashicorp/vagrant/issues/10575#issuecomment-458703686

I have a helper added to the plugin to forcibly clear any existing port forwards to make it easy to "start from scratch" and will be included in the next release.

**Comment by chrissphinx** [comment]
@chrisroberts yes, I had seen that thread, but unfortunately removing the file just gives me:

```
> vagrant up
Bringing machine 'default' up with 'vmware_desktop' provider...
==> default: Cloning VMware VM: 'bento/ubuntu-16.04'. This can take some time...
==> default: Checking if box 'bento/ubuntu-16.04' version '201812.27.0' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for the VM to receive an address...
==> default: Forwarding ports...
    default: -- 22 => 2222
Vagrant failed to apply the requested port forward. The following
error message was generated while attempting to apply the port
forward rule:

  Port forward conflict on host port 2222

Please resolve any problems reported in the error message above and
try again.
```

😞

**Comment by chrisroberts** [comment]
The `/Library/Preferences/VMware Fusion/networking` and `/Library/Preferences/VMware Fusion\vmnet8\nat.conf` are where VMware stores it's networking configuration and may still have the forwards defined if the error persists.

**Comment by chrissphinx** [comment]
So, tried once more to bring it up and checked these files before and after, they appeared to be there same. Here is a gist with their contents: https://gist.github.com/chrissphinx/9b89e9ab87e1705b855551ea72cffc13

I think #10526 is related ...

**Comment by chrisroberts** [comment]
If they are empty, and the settings nat.json file in the plugin directory is empty and/or removed, the only possible option is that the utility has the forward cached internally and restarting the utility service will clear it out.

**Comment by chrissphinx** [comment]
I tried this today and was back to:
```
Bringing machine 'default' up with 'vmware_desktop' provider...
==> default: Cloning VMware VM: 'bento/ubuntu-16.04'. This can take some time...
==> default: Checking if box 'bento/ubuntu-16.04' version '201812.27.0' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for the VM to receive an address...
==> default: Forwarding ports...
    default: -- 22 => 2222
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection refused. Retrying...
    etc...
```

I checked `/opt/vagrant-vmware-desktop/settings/nat.json` to find:

```
{
  "fwds": [
    {
      "enable": false,
      "device": "8",
      "protocol": "tcp",
      "hostport": 2222,
      "guestip": "192.168.120.179",
      "guestport": 22,
      "description": "vagrant: /users/sphinx/ctf/.vagrant/machines/default/vmware_desktop/a5c9b98b-9634-443d-af1d-37640dc05fc0/ubuntu-16.04-amd64.vmx"
    }
  ]
}
```

So, I tried to change "enable" to `true` but `vagrant ssh` returns -1 status code. I used `launchctl stop com.vagrant.vagrant-vmware-utility` a few times,  but there is no change.

`/Library/Preferences/VMware\ Fusion/networking` has this line:

```
add_nat_portfwd 8 tcp 2222 192.168.120.179 22 vagrant: /users/sphinx/ctf/.vagrant/machines/default/vmware_desktop/a5c9b98b-9634-443d-af1d-37640dc05fc0/ubuntu-16.04-amd64.vmx
```

Again I'm able to SSH to that IP (`192.168.120.179`) using the insecure key in `~/vagrant.d` and with default username/password. Should I be able to ssh to `localhost:2222` according to this port forward? Because that returns connection refused...

**Comment by eightbitdino** [comment]
I had this issue with Linux (Fedora 29) as well.  VBox provisions fine, but VMWare choked.  I had to stop the vagrant-vmware-utility (systemctl stop vagrant-vmware-utility) and delete /opt/vagrant-vmware-desktop/settings/nat.json on one of my systems because it didn't seem to be clearing on it's own and a daemon restart didn't help.  Once I rebooted the system, it seems to be working properly.  I have another system with the same problem that seems to be running the newest version of vagrant-vmware-utility and is also getting the "Connection refused: Retrying..." loop.  I've wiped the local .vagrant directory and the .vagrant.d directory in my home directory before without any luck.  I'm going to try reinstalling the utility to see if that helps, but this is definitely aggravating.  Two machines boot and then it immediately chokes.

**Comment by ryanolton** [comment]
Vagrant: 2.2.9
Vagrant VMWare Desktop: 2.1.1
Vagrant VMWare Utility: 1.0.9
VMware: Workstation 15 Pro 15.5.6 build-16341506
Host: Pop!_OS 20.04 (Ubuntu 20.04)
Guest: 64-bit Debian 10 (generic/debian10)

### Vagrantfile

```
config.vm.define "blah", primary: true do |blah|
  blah.vm.box = "generic/debian10"

  blah.vm.network "public_network", use_dhcp_assigned_default_route: true
  blah.vm.network "forwarded_port", guest: 22, host: 22400, id: "ssh", auto_correct: true
end
```

I stumbled across this issue trying to fix this very same thing on Linux (Ubuntu/Debian) using VMWare Workstation 15.5.6 Pro. I get the exact same "Connection refused: Retrying..." issue, but in my case it's only for one single machine -- all the other machines come up fine. I have used --debug to trace it back to the step where the forward is applied.

On the working machines, when the SSH port is forwarded, I can see the forward appear in netstat (sudo netstat -ntlp | grep LISTEN). On the machine that fails, Vagrant says the forward happened, but I never see the forward appear in netstat.

I've stopped the vagrant-vmware-utility (systemctl stop vagrant-vmware-utility), deleted /opt/vagrant-vmware-desktop/settings/nat.json, and then restarted the vagrant-vmware-utility, but this does nothing.

I can login into the box manually using a username and password (via the GUI portion of VMWare Workstation) and can confirm that SSH is running.

Is there somewhere I can be looking (perhaps via --debug) that tells me more about a failed port mapping? As far as I can tell (via --debug), Vagrant "believes" the forward worked and doesn't mention any issues during this step.

### vagrant up --debug blah

```
 INFO interface: info: Forwarding ports...
 INFO interface: info: ==> blah: Forwarding ports...
==> blah: Forwarding ports...
 INFO interface: detail: -- 22 => 22400
 INFO interface: detail:     blah: -- 22 => 22400
    blah: -- 22 => 22400
DEBUG vmware_driver: requesting ports to be forwarded: [{:device=>"vmnet8", :guest_port=>22, :host_port=>22400, :protocol=>"tcp", :guest_ip=>"172.16.70.144"}]
DEBUG vmware_driver: forwarding ports via collection method
DEBUG vagrant_utility: request METHOD=PUT PATH=/vmnet/vmnet8/portforward RESPONSE=200 
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::WaitForCommunicator:0x00007f12b0788218>
 INFO interface: output: Waiting for machine to boot. This may take a few minutes...
 INFO interface: output: ==> blah: Waiting for machine to boot. This may take a few minutes...
==> blah: Waiting for machine to boot. This may take a few minutes...
```
```
 INFO ssh: Attempting SSH connection...
 INFO ssh: Attempting to connect to SSH...
 INFO ssh:   - Host: 127.0.0.1
 INFO ssh:   - Port: 22400
 INFO ssh:   - Username: vagrant
 INFO ssh:   - Password? false
 INFO ssh:   - Key Path: ["/home/ryan/.vagrant/machines/blah/vmware_desktop/private_key"]
DEBUG ssh:   - connect_opts: {:auth_methods=>["none", "hostbased", "publickey"], :config=>false, :forward_agent=>false, :send_env=>false, :keys_only=>true, :verify_host_key=>:never, :password=>nil, :port=>22400, :timeout=>15, :user_known_hosts_file=>[], :verbose=>:debug, :logger=>#<Logger:0x0000000003b2b418 @level=0, @progname=nil, @default_formatter=#<Logger::Formatter:0x0000000003b2b238 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x0000000003b2b0a8 @shift_period_suffix=nil, @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<StringIO:0x0000000003b2b5f8>, @mon_mutex=#<Thread::Mutex:0x0000000003b2af68>, @mon_mutex_owner_object_id=31021140, @mon_owner=nil, @mon_count=0>>, :keys=>["/home/ryan/.vagrant/machines/blah/vmware_desktop/private_key"], :remote_user=>"vagrant"}
DEBUG ssh: == Net-SSH connection debug-level log START ==
DEBUG ssh: D, [2020-07-12T13:28:37.626961 #26739] DEBUG -- net.ssh.transport.session[1da3850]: establishing connection to 127.0.0.1:22400

DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH not ready: #<Vagrant::Errors::SSHConnectionRefused: SSH connection was refused! This usually happens if the VM failed to
boot properly. Some steps to try to fix this: First, try reloading your
VM with `vagrant reload`, since a simple restart sometimes fixes things.
If that doesn't work, destroy your VM and recreate it with a `vagrant destroy`
followed by a `vagrant up`. If that doesn't work, contact a Vagrant
maintainer (support channels listed on the website) for more assistance.>
 INFO interface: detail: Warning: Connection refused. Retrying...
 INFO interface: detail:     blah: Warning: Connection refused. Retrying...
    blah: Warning: Connection refused. Retrying...
```
If I manually add this forward via the Virtual Network Editor (VMWare Workstation tool; vmware-netcfg), the machine begins working as expected. However, subsequent `vagrant up` or `vagrant reload` causes this forward to not be created, leading to same issues. For some reason VMWare is not creating the forward correctly and Vagrant is unaware.

**Comment by chrisroberts** [comment]
Hi there,

The end of this issue revolved around port conflict errors with the VMware provider. The `vagrant-vmware-utility` which is part of the Vagrant VMware provider plugin has an updated port forwarding implementation which utilizes the vmrest interface and now provides more consistent behavior. Upgrading to the latest version should resolve these issues.

I'm going to close this issue now, but if you are still experiencing these issues, please open a new issue and we will investigate further.

Thanks!

**Comment by vohi** [comment]
I still experience the issue now and again on a macOS 10.14 host.

I am running plugin version 2.0.1

```
$ vagrant plugin list
opennebula-provider (1.1.5, global)
  - Version Constraint: > 0
vagrant-aws (0.7.2, global)
  - Version Constraint: > 0
vagrant-azure (2.0.0, global)
  - Version Constraint: > 0
vagrant-vmware-desktop (2.1.2, global)
  - Version Constraint: > 0
```

which seems to be the latest.

The most reliable remedy seems to be to

* wipe out /opt/vagrant-vmware-desktop/settings/nat.json
* stop and restart com.vagrant.vagrant-vmware-utility via launchctl

After doing that, the port collision error goes away. What triggers the error (occasionally, and not very often) is destroying a running VM (I have a multi-machine setup, don't think that's related), which then prints

```
==> machine10: Deleting the VM...
Vagrant encountered an error while attempting to prune unused
port forward entries:

  Failed to delete port forward
```
