### ISSUE TITLE
Enhancement Request: Allow Google Drive link as box url

### ISSUE THREAD

**Issue by W1M0R** [hashicorp/vagrant#11734]
**Is your feature request related to a problem? Please describe.**
Downloading boxes from the Vagrant cloud takes a very long time (see issue #5319). Uploading the box to Google Drive and downloading it from there is much faster. However, specifying the box_url using the publicly shared Google Drive link, does not work, failing with the error: 

```
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

bsdtar.EXE: Error opening archive: Unrecognized archive format
```

**Describe the solution you'd like**
I would like Vagrant to support Google Drive links in box_url.

**Describe alternatives you've considered**
I have converted the Google Drive url to an alternative representation that specifically requests export as download, but this also produced the same error message. Another approach, is to download the file beforehand, and use a `file:` box_url.

Here is a link describing the effort involved to download a large file from Google Drive in an automated way: https://stackoverflow.com/questions/25010369/wget-curl-large-file-from-google-drive

**Comment by briancain** [comment]
Hey there @W1M0R - box_url isn't exactly what you think it might be. It's expecting a metadata box file format, which includes a URL (in your case a google drive URL) to the physical asset, along with some additional metadata for Vagrant. You can read more about that format here: https://www.vagrantup.com/docs/boxes/format#box-metadata

Pointing Vagrant at your json metadata file should resolve the issue. Thanks!

**Comment by W1M0R** [comment]
Thanks for clearing that up for me. Even if I use json metadata and specify the box url as a link to a Google drive resource, it still doesn't work, but I believe this is because of how Google treats large files. It requires some special treatment. Is this something that Vagrant would consider supporting, that is, detecting Google drive links and handling them appropriately?

**Comment by briancain** [comment]
@W1M0R - no, I don't think Vagrant would support the workflow required for downloading Vagrant boxes from google drive. Vagrant Cloud offers free hosting for boxes and that's what the majority of Vagrant users use. Otherwise if you wish to host your own, Vagrant can still download a box if it's available directly to download. For example I know other folks use Dropbox for this, as it gives you the ability to generate direct download URLs for public assets.

You might be able to write a ruby script that your Vagrantfile uses that grabs the direct URL from google drive and places it as a variable for `box_url`, similar to what this does: https://github.com/circulosmeos/gdown.pl Or manually download the box and add the file with `vagrant box add` if you wish to continue using google drive.
