### ISSUE TITLE
SMB mount broken since 2.2.15

### ISSUE THREAD

**Issue by McBochi** [hashicorp/vagrant#12277]
### Vagrant version

Vagrant 2.2.15

### Host operating system

Windows 10 - Version 20H2 (Build 19042.906)

### Guest operating system

hashicorp/bionic64

### Vagrantfile

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_check_update = false

  config.vm.provider "hyperv" do |h|
    h.vmname = "myapplication"
    h.cpus = 1
    h.memory = 1536
    h.enable_checkpoints = false
  end

  config.vm.synced_folder ".", "/vagrant", type: "smb", owner: "www-data", group: "www-data"

  config.vm.provision "shell", inline: <<-SHELL
    # Some installation / setup stuff
  SHELL

end
```

Pretty basic Vagrantfile, which is wasn't changed lately and ran without issues in Vagrant 2.2.14.

### Debug output

https://gist.github.com/McBochi/06cfe6aaf2a7b0d17a4c4486f0a6633c

### Expected behavior

After the prompt for username and password for the SMB share, the folder should be mounted and usable in the guest system.

### Actual behavior

Starting with Vagrant 2.2.15, it fails when trying to mount the share with:
```
C:/HashiCorp/Vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/synced_folders/smb/cap/mount_options.rb:48:in 'mount_name': wrong number of arguments (given 2, expected 3) (ArgumentError)
```

### Steps to reproduce

1. Take the above Vagrantfile.
2. Call `vagrant up`
3. Provide credentials as usual.

### References

It might be related to the latest changes for vbox shared folders:
https://github.com/hashicorp/vagrant/commit/b30a87ce6cb7e5a4398f236baa5574b2d5e6143f#diff-befa3878a0f7ad26bb3669d9239b56d17d90bf3b99a9f3dbd07b57c929c0876f

**Comment by lexxxel** [comment]
I do have the same issue.

**Comment by McBochi** [comment]
Just applied the diff and it works like a charm. Thanks for the quick and easy fix, @soapy1 ! :)

**Comment by ElijahTailor** [comment]
The bug is present @ hyper-v + generic/ubuntu2004 box environment also. Same situation, same error.

**Comment by ALERTua** [comment]
please fix this issue. it affects hundreds of people in my community. thank you.

**Comment by can-acar** [comment]
C:/HashiCorp/Vagrant/embedded/gems/2.2.15/gems/vagrant-2.2.15/plugins/synced_folders/smb/cap/mount_options.rb
row 48 in `mount_name': wrong number of arguments (given 2, expected 3) (ArgumentError) 



Orginal :
`def self.mount_name(machine, name, data) 
  data[:smb_host] ||= machine.guest.capability( :choose_addressable_ip_addr, candidate_ips) 
  "//#{data[:smb_host]}/#data[:smb_id]}"
  end`

I fixed: deleted name parameter.  "name" parameter is not use in function 

` def self.mount_name(machine,  data)
          data[:smb_host] ||= machine.guest.capability(
            :choose_addressable_ip_addr, candidate_ips)
          "//#{data[:smb_host]}/#{data[:smb_id]}"
        end`

thanks

**Comment by cbj4074** [comment]
@can-acar That eliminates the exception, but then none of the shares are mounted once the VM boots.

Per @soapy1 's [linked pull request](https://github.com/hashicorp/vagrant/pull/12281), appropriate workaround is actually the reverse of what you suggest: add the missing argument to the calling context (rather than remove it from the callee).

In other words, add `name` as the second argument in https://github.com/hashicorp/vagrant/blob/9247e07fc8ffe2fdb91c6422bbb133a25983fe15/plugins/guests/linux/cap/mount_smb_shared_folder.rb#L23 

such that it looks like this:

```
mount_device = options[:plugin].capability(:mount_name, name, options)
```



So, anyone who needs a "quick-fix" for this until it's tagged and released can make the above edit manually.

**Comment by SamilMehdiyev** [comment]
**Vagrant version**
Vagrant 2.2.15

**Host operating system**
Windows 10

**Guest operating system**
hashicorp/precise64

**Vagrantfile**
```
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.synced_folder ".", "/vagrant"
end
```

Still the same issue exist.

**Comment by Pyker** [comment]
> **Vagrant version**
> Vagrant 2.2.15
> 
> **Host operating system**
> Windows 10
> 
> **Guest operating system**
> hashicorp/precise64
> 
> **Vagrantfile**
> ```
> Vagrant.configure("2") do |config|
>   config.vm.box = "hashicorp/precise64"
>   config.vm.synced_folder ".", "/vagrant"
> end
> ```
> 
> Still the same issue exist.

It's fixed in 2.2.16. You're running 2.2.15 (the version it's broken on).
