### ISSUE TITLE
Revoked Hashicorp certificate for msi installer

### ISSUE THREAD

**Issue by jowko** [hashicorp/vagrant#13051]
### Expected behavior

Vagrant should be installed correctly without issues on Windows machine.

### Actual behavior

Vagrant cannot be installed because of the Windows security error.
Package was signed with certificate which was revoked by certificate authority. New certificate should be issued and it should be used to sign windows installation packages
![error](https://user-images.githubusercontent.com/20277750/211313792-fe0355f6-6642-48e6-a3ac-fb77d369f5d8.jpg)
![certificate](https://user-images.githubusercontent.com/20277750/211313748-afeab391-d55d-4e55-a12d-cbf30c51f7ca.png)

#### Vagrant version

2.3.4 AMD64
Windows 10

#### Steps to reproduce

1. Download msi package for windows installation
2. Try to install it with high security settings in windows

**Comment by Dr-Kobi** [comment]
Hey, I just got it to work. Open your cmd prompt and run this 

MsiExec.exe /i "C:\Users\user\Downloads\vagrant_2.3.3_windows_amd64.msi"

it needs the location and, obviously replace the path, but you should be good to go

**Comment by DMaxter** [comment]
I am also facing the same issue, and the solution provided by @Dr-Kobi doesn't work, it shows an error stating that it cannot open the installer

This issue affects all versions (including) from 2.2.7 to 2.3.4

**Comment by jowko** [comment]
@Dr-Kobi I managed to install it using this hack the same day I reported it but this is ugly workaround which should not be used because it's may compromise security.

New certificate should be issued and used at least for the newest versions.

**Comment by longestdrive** [comment]
Same problem for me - I assumed it related to UAC in windows and went as far as re-installing windows :(

**Comment by maddhatter** [comment]
Same problem here - honestly, trying to work around a revoked certificate is a non-starter for me. If there was a reason to revoke the certificate, then the code it signed can't trustworthy. Any workarounds eliminate the point of code signing.

Windows is 100% behaving as I would want it to and blocking execution.

**Comment by Dr-Kobi** [comment]
Hmmm,I'm sorry it didn't work. 

Oh! I forgot. I did have to turn off the alerts in the control panel first. Did you all happen to do that? 

I need it for a class, so that's why. But if it's not a significant need for you then I understand.

The certificate is revoked for hashicorp itself so it wouldn't matter which version because it will affect all of them.

**Comment by chrisroberts** [comment]
Hi everybody,

The certificate authority HashiCorp uses incorrectly noted the revocation date of our Windows signing cert when it was revoked in error. We have been working with our certificate authority to fix the error and as of midday January 10, 2023, the revocation record has been fixed. This should fix errors seen with our Windows installer. Note: The existing key expires January 20, 2023, and we will be signing future releases with a new key. 

If you are still encountering errors when attempting to run the installer, you may need to clear the CRL cache which can be done using the following command:

```
certutil -URLCache CRL delete

**Comment by gsi-85** [comment]
Hi,

The suggested:
`certutil -URLCache CRL delete`
Isn't making any difference for me.
Still getting the same message...

**Comment by pszlazak** [comment]
OK, finally certificate in `vagrant_2.3.4_windows_amd64.msi` is reported as OK (no longer as revoked). Looks like you simply need to wait.

**Comment by longestdrive** [comment]
Just downloaded fresh version and cleared the cache as above but still blocked by UAC - sadly not fixed for me

**Comment by DMaxter** [comment]
I'm still getting the same error. The signature of the last binary is from December 10, so it is still using the revoked key

I think this issue should be reopened
