### ISSUE TITLE
Get current provider in Vagrantfile

### ISSUE THREAD

**Issue by p0deje** [hashicorp/vagrant#1867]
It would be great to have some API to get the current provider in `Vagrantfile`. Something like:

``` ruby
Vagrant.configure('2') do |config|
  config.vm.provider :virtualbox do |vbox, override|
    # some code
  end

  config.vm.provider :vmware_fusion do |vmware, override|
    # some code
  end

  config.vm.provider :kvm do |_, override|
    # some code
  end

  unless config.vm.provider == :kvm
    config.vm.network :forwarded_port, guest: 1080, host: 1080
    config.vm.network :forwarded_port, guest: 3000, host: 3000
    config.vm.synced_folder '.', '/vagrant', nfs: true
  end
end
```

I suppose I can still get this info by some internals, but I didn't manage to find a way through.

P.S. Would be happy to send PR if anyones knows where I can get current provider info.

**Comment by kenorb** [comment]
Answering the title question:

```
require 'getoptlong'
opts = GetoptLong.new(
  [ '--provider', GetoptLong::OPTIONAL_ARGUMENT ]
)

provider='virtualbox'
opts.each do |opt, arg|
  case opt
    when '--provider'
      provider=arg
  end
end

Vagrant.configure(2) do |config|
  config.vm.define "default-#{provider}" do |box|
  end
end
```

**Comment by stevekuznetsov** [comment]
@kenorb since the Vagrantfile is loaded and run on every single `vagrant` command line invocation (why??), the `getoptlong` hack breaks CLI interactions with Vagrant.

```
    $ vagrant ssh-config --help
    Usage: vagrant ssh-config [options] [name]
     
    Options:
     
            --host NAME                  Name the host for the config
        -h, --help                       Print this help
    /usr/share/vagrant/bin/vagrant: unrecognized option `--help'
    There was an error loading a Vagrantfile. The file being loaded
    and the error message are shown below. This is usually caused by
    a syntax error.
     
    Path: /home/skuznets/.config/origin-ci-tool/vagrant/Vagrantfile
    Line number: 394
    Message: GetoptLong::InvalidOption: unrecognized option `--help'
    vagrant$ vagrant ssh-config --host=default
    /usr/share/vagrant/bin/vagrant: unrecognized option `--host'
    There was an error loading a Vagrantfile. The file being loaded
    and the error message are shown below. This is usually caused by
    a syntax error.
     
    Path: /home/skuznets/.config/origin-ci-tool/vagrant/Vagrantfile
    Line number: 394
    Message: GetoptLong::InvalidOption: unrecognized option `--host'
```

**Comment by kenorb** [comment]
@stevekuznetsov To ignore the error for other command you can add empty `rescue` I guess, I've updated the code. It shouldn't fail, however it'll always show _unrecognized option_. See this [post](http://stackoverflow.com/a/38315929/55075).

**Comment by mloskot** [comment]
Although I'm fairly experienced with Vagrant, I may not be fluent in Ruby, so I may be missing something here. But, this issue asked question how to "Get current provider in Vagrantfile" which is still not answered.

Is there really no env or constant that can be checked to test for current provider?
