### ISSUE TITLE
Error Creating VM With Vagrant 1.3.5 and VirtualBox 4.3.0

### ISSUE THREAD

**Issue by pauloelr** [hashicorp/vagrant#2392]
Hi,

I'm having this error:

``` Shell
Bringing machine 'default' up with 'virtualbox' provider...
[default] Importing base box 'precise64'...
[default] Matching MAC address for NAT networking...
[default] Setting the name of the VM...
[default] Clearing any previously set forwarded ports...
[default] Creating shared folders metadata...
[default] Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_INVALIDARG
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Assertion failed: [!aGuid.isValid()] at 'D:\tinderbox\win-4.3\src\VBox\Main\src-server\HostNetworkInterfaceImpl.cpp' (74) in long __cdecl HostNetworkInterface::init(class com::Bstr,class com::Bstr, class com::Guid,enum __MIDL___MIDL_itf_VirtualBox_0000_0000_0034).
VBoxManage.exe: error: Please contact the product vendor!
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterface, interface IHostNetworkInterface
VBoxManage.exe: error: Context: "int __cdecl handleCreate(struct HandlerArg *,int,int *)" at line 66 of file VBoxManageHostonly.cpp
```

 when running `vagrant up` on Windows 8 Host to create a new virtual machine with the following Vagrantfile

``` Ruby
Vagrant.configure("2") do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.network :private_network, ip: "192.168.2.3"
  config.vm.network "public_network"
  config.ssh.forward_agent = true

  #[...]

  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--nictype1", "virtio"]
    v.customize ["modifyvm", :id, "--nictype2", "virtio"]
    v.customize ["modifyvm", :id, "--nictype3", "virtio"]
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--name", "VagrantMachineTest"]
  end

  #[...]

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.module_path = "puppet/modules"
    puppet.manifest_file  = "default.pp"
    puppet.options = ['--verbose']
  end
end
```

The problem is solved commenting this line:

``` Ruby
#config.vm.network :private_network, ip: "192.168.2.3"
```

I was executing the same Vagrantfile with Vagrant 1.3.3 and VirtualBox 4.2.x without any error, but i had to update VirtualBox due to incompatibility of the previous version with Kernell 3.11 on other non-Vagrant machines so i upgraded Vagrant to 1.3.5 either for compatibility.

I've tried already run `VirtualBox.exe restart` without success

But i really need to configure private_network on my VM, so i'm asking if there is something i can do to bypass this error even temporally?

Thanks

**Comment by dianniu** [comment]
4.3.26有bug，换成4.3.24就正常了，覆盖安装不影响之前配置的虚拟机

**Comment by panique** [comment]
@dianniu Why the hell are you commenting in chinese or whatever this language is ? Nobody is able to understand you. What is wrong is these people ?

**Comment by QuietOmen** [comment]
@pauloelr your solution worked for me. Thank you.

**Comment by helgatheviking** [comment]
@gmanfunky I know it has been almost 2 years, but the problem still exists in VirtualBox 4.3.28 + Win 7. Your solution is the only thing that worked for me after several hours of searching. Thank you!

**Comment by dianniu** [comment]
Virtualbox 4.3.26 buggy, change to 4.3.24 is normal, reinstall does not affect the virtual machine configuration.This is the simplest solution

**Comment by Master-Chief-2007** [comment]
Will confirm.... I also installed VirtualBox 4.3.24 after a lot of frustration. (Should 'v found the bottom of this thread sooner!) . I am also using Windows 7 as host.
Now it is resolved. Phew!
Thanks to all who have commented above.

Just for reference or search engines, my log output was:
```
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "int __cdecl handleCreate(struct HandlerArg *,int,int *)" at line 68 of file VBoxManageHostonly.cpp

```

**Comment by MichelAraujo** [comment]
I'm having this same problem now with windows 10

**Comment by sensui7** [comment]
Hey, @MichelAraujo , @pauloelr 's method still works for **windows 10**.


You don't  need to uninstall or restart anythings. Below  is under *VirtualBox 5.0* ,

1. Run VirtualBox(GUI program)
2. press ALT-F then ALT-G to open the 'global settings'( I am not sure what the menu text in English.)

3. Network->Host-only Networks

Edit the adapter which has the maximum number with the address match your vagrant settings. 
In my machine,  the ip of vagrant box is : "192.168.10.10",(check it in the .yaml file under your box directory), so I fill the #3 adapter' field with 192.168.10.1 and 255.255.255.0. 

4. close VirtualBox GUI and Run :vagrant up .

**Comment by jeremiahgibson91** [comment]
Thanks, @Sensui7.

This fixed the issue I was having as well. Same one as above. deleted all the unused adapaters edited the highest one and ran vagrant up. Thanks!

**Comment by panique** [comment]
FYI Vagrant is on 1.7.x now, VirtualBox on 5.x, so may I ask the poeple still having the problem: Which versions are you using ?

**Comment by pietervanh** [comment]
Still happening Vagrant 1.7.4 and VirtualBox 5.0.0
Can we bypass that vagrant doesn't remove / create the network adapters?

**Comment by ITDudeJeroen** [comment]
I had the same problem after installing Windows 10.
Changing the host-only network finaly fixed the problem for me.

I first installed the latest VirtualBox 5 and Vagrant 1.7.4 which didn't help but after changing the host-only network it started working again.

Thank you @pauloelr

**Comment by Reklino** [comment]
@ITDudeJeroen  I am still having this issue on Windows 10 and can't seem to get it working by changing the host-only network. Can you share your settings?

**Comment by Reklino** [comment]
I ended up finding a solution for this here: https://laracasts.com/discuss/channels/general-discussion/windows-10-vagrant-virtualbox-homestead

**Comment by yellajaswanth** [comment]
Uff Finally!! Thanks @sensui7 
That fixed the issue.

**Comment by bjorngrunde** [comment]
I can confirm @gmanfunky is right. Uninstalled virtualbox 5.0 and installed 5.0.2 on Windows 10. worked like a charm.

**Comment by bambangsarif** [comment]
Thanks @sensui7 
I did the opposite, change the vagrantfile setting to match the virtualbox's host-only adapter network address. It works.

**Comment by tuvietthao** [comment]
Just turn off your Hyper-V and restart your computer. That worked for me

**Comment by aelsharif** [comment]
This worked for me: Open Virtualbox and remove the VM then run vagrant up. This is an easy fix. No need to uninstall anything.
