### ISSUE TITLE
Vagrant can't mount shared folder in VirtualBox 4.3.10

### ISSUE THREAD

**Issue by wsouto** [hashicorp/vagrant#3341]
I got VirtualBox updated to 4.3.10 via ppa last night (which I'll downgrade to 4.3.8 and disable this PPA so I can manually control upgrades) and Vagrant is failing to mount shared folder with this new version. The guest additions was upgraded too in an already working VM, I also tried to install it in a new VM with no previous guest additions installed but no success...

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 80 => 8080 (adapter 1)
    default: 3000 => 3000 (adapter 1)
    default: 5432 => 5432 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Error: Connection timeout. Retrying...
==> default: Machine booted and ready!
GuestAdditions 4.3.10 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /home/wsouto/Projetos/printo
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` /vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` /vagrant /vagrant
```

```
$ lsmod
Module                  Size  Used by
vboxsf                 42558  0 
vesafb                 13500  1 
nfsd                  247847  2 
auth_rpcgss            48552  1 nfsd
nfs_acl                12733  1 nfsd
nfs                   156370  0 
microcode              18894  0 
lockd                  78549  2 nfs,nfsd
sunrpc                230213  6 nfs,nfsd,auth_rpcgss,lockd,nfs_acl
fscache                55868  1 nfs
vboxguest             219348  2 vboxsf
ahci                   25579  2 
libahci                26619  1 ahci
```

It is a problem with VB 4.3.10 for sure, but I'm reporting here to others can know about this issue.

**Comment by dmuth** [comment]
Still seeing this happen with Virtualbox 4.3.20 and 4.3.20 of the extension packs with Ubuntu Trusty (14.04) downloaded from https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box.

I honestly don't even understand why this is happening across so many versions.

I think it's time to take a step back and look at how the problem is being approached, because this has been affecting many people over many months, and is causing many frustrated developers.

**Comment by ChrisAntaki** [comment]
`vagrant plugin install vagrant-vbguest` fixed the issue for me, thanks

**Comment by Hesesses** [comment]
```
vagrant plugin install vagrant-vbguest

Installing the 'vagrant-vbguest' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing nokogiri (1.6.5), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.6.5'` succeeds before bundling.
```

Any ideas?

**Comment by ChrisAntaki** [comment]
@Hesesses Installing `nokogiri` is actually unrelated to this issue. That said - try this.

```sh
# Install Nokogiri
sudo yum install gcc ruby-devel libxml2 libxml2-devel libxslt libxslt-devel -y
# On AWS you may need to use '$ gem install nokogiri -- --use-system-libraries'
gem install nokogiri --use-system-libraries
```

**Comment by Hesesses** [comment]
@ChrisAntaki 
'yum: command not found'

I had everything working, then reloaded the vagrant and getting the 'Failed to mount folders in Linux guest.' 

Any other ideas?

**Comment by ChrisAntaki** [comment]
@Hesesses Which version of Linux are you using?

**Comment by Hesesses** [comment]
@ChrisAntaki http://laravel.com/docs/4.2/homestead

**Comment by ChrisAntaki** [comment]
@Hesesses Try replacing `yum` with `apt-get` (Laravel Homestead uses Ubuntu)

**Comment by Hesesses** [comment]
```
vagrant@homestead:~$ sudo apt-get install gcc ruby-devel libxml2 libxml2-devel libxslt libxslt-devel -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ruby-devel
E: Unable to locate package libxml2-devel
E: Unable to locate package libxslt
E: Unable to locate package libxslt-devel
```

**Comment by ChrisAntaki** [comment]
@Hesesses Those packages will have different names on Ubuntu's package manager. Wish I could help more.

**Comment by Hesesses** [comment]
@ChrisAntaki Thank you for your time! Do you think should I try to update VirtualBox to latest version? I have 4.3.10 now

**Comment by stephen-mw** [comment]
The newest version of vagrant-vbguest (0.10.0) will automatically upload and compile a proper version of guest additions if your host was built without it or improperly.

I personally had to change my packer configuration to create the necessary symlink to prevent this from being recompiled.

**Comment by tonkonogov** [comment]
I have faced with the same trouble. I'm trying to configure a shared folder by smb with win8 as host and ubuntu 14.10 as a guest system. 
As it proposed above, I have installed `vagrant-vbguest (0.10.0)`, but have no luck with it, still got that error. But I have found one more workaround: when vagrant up script showed me up a error log, I just removed from that lines a `sec=ntlm` part and run it again with sudo in ssh.
For example, vagrant give me:

    mount -t cifs -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3`,sec=ntlm,username=USER,pass=PASS //172.16.1.142/my_hash /my_mount_point

I remove `sec=ntlm` in the line and add sudo in order to run it in command line:

    sudo mount -t cifs -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3`,username=USER,pass=PASS //172.16.1.142/my_hash /my_mount_point

And it was enough for me, now it works as supposed. 

The only question for me - what does exactly the ntlm security option do there? Is it strongly required or may be omitted?
My version of VB and guest additions is `4.3.20`.

**Comment by dmuth** [comment]
Just an update for everyone, I had this start happening out of the blue on my Macbook Pro with CoreOS, using these VagrantFile directives:

`config.vm.synced_folder ".", "/home/core/vagrant", 
    id: "core", :nfs => true, :mount_options   => ['nolock,vers=3,udp']
`

I eventually rebooted my machine, and now it works with no issues.

This suggests that there is an issue in OS/X with regards to how state is kept, which clears out on reboot.

No, we shouldn't have to reboot our machines just to run a VM properly, but it may provide a clue as to the underlying cause.

**Comment by mlt** [comment]
This issue comes up while searching for `Invalid argument` error from *mount.vboxsf*. For the sake of completeness [another reason that results in failed mount with Windows host might be junction points in NTFS.](https://www.virtualbox.org/ticket/12819) Start VM only from original folder and not a linked one.

**Comment by milesstewart88** [comment]
@renanvaz thanks!

**Comment by gregsandell** [comment]
I am on Mac OSX and have found a completely different solution to this problem.  I run into it every time I run vagrant halt followed by vagrant up again.

Even though your vagrant up ended in failure, vagrant is running.  Go into the ssh with the vagrant ssh command.  Then go to all the places where mount points had been previously installed.  Those will of course all be empty.  Delete all of those directories and run vagrant up again.

**Comment by montogeek** [comment]
I have CentOS 6.2 as guest machine and OSX Yosemite as host machine, installing 
`vagrant plugin install vagrant-vbguest` solved my problem :)

**Comment by mikulely** [comment]
`vagrant plugin install vagrant-vbguest` works for me. Ubuntu 14.02 geust, OSX Yosemite  host.

**Comment by samjulien** [comment]
I have tried `vagrant plugin install vagrant-vbguest` with and without the symbolic link command after a `vagrant ssh` and it's still failing to mount the folder. Guest is ubuntu/trusty64, host is Windows 8.1. I'm running the console in Administrator mode, if that's relevant. The error is:

`Failed to mount folders in Linux guest. This is usually because the "vboxsf" file system is not available.`

Any ideas?

**Comment by Neetuj** [comment]
tried vagrant plugin install vagrant-vbguest, tried $ sudo ln -s /opt/VBoxGuestAdditions-4.3.10/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions

and i am still running into :-1: 

Failed to mount folders in Linux guest. This is usually beacuse
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` /vagrant /vagrant
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` /vagrant /vagrant
~/office/bm-ansible > vagrant plugin install vagrant-vbguest

**Comment by Neetuj** [comment]
~/office/bm-ansible > vagrant --version 
Vagrant 1.4.3
~/office/bm-ansible > lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS

geust i am trying to sping  is CentOS7.0 x86_64 minimal

**Comment by aohx075** [comment]
Also running into this issue despite having installed vagrant-vbguest and creating the symlink.

Running:
* virtualbox 4.3.26 (upgraded it to see if it fixes the problem).
* host = OSX (Yosemite)
* guestOS = CentOS7.0 x86_64 minimal

**Comment by clayreimann** [comment]
:+1: `vagrant plugin install vagrant-vbguest` OS X 10.10 Centos-6.5

**Comment by clayreimann** [comment]
:-1: and now it's broken again :disappointed:

**Comment by guillaume-brossard-adsk** [comment]
This is a nightmare. Every now and then this issue come back, when a new version is released. This is really frustrating.
OSX 10.10.3
Virtual Box 4.3.26
Vagrant 1.7.2

```
Installing Virtualbox Guest Additions 4.3.26 - guest version is 4.3.20
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.3.26 Guest Additions for Linux............
VirtualBox Guest Additions installer
Removing installed version 4.3.26 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
Removing existing VirtualBox non-DKMS kernel modules[  OK  ]
Building the VirtualBox Guest Additions kernel modules
Building the main Guest Additions module[FAILED]
(Look at /var/log/vboxadd-install.log to find out what went wrong)
```

In the log, I can see 2 errors:
```
grep: /lib/modules/3.10.0-123.el7.x86_64/build/include/linux/version.h: No such file or directory
make KBUILD_VERBOSE=1 CONFIG_MODULE_SIG= -C /lib/modules/3.10.0-123.el7.x86_64/build SUBDIRS=/tmp/vbox.0 SRCROOT=/tmp/vbox.0 modules
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (		\
echo >&2;							\
echo >&2 "  ERROR: Kernel configuration is invalid.";		\
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";	\
echo >&2 ;							\
/bin/false)
```
```
Creating user for the Guest Additions.
Creating udev rule for the Guest Additions kernel module.
/tmp/vbox.0/Makefile.include.header:115: *** Error: unable to find the include directory for your current Linux kernel. Specify KERN_INCL=<directory> and run Make again.  Stop.
```

**Comment by rkJun** [comment]
> Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

> mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3` /vagrant /vagrant
> mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant` /vagrant /vagrant


I have Ubuntu 14.04 (64bit) as guest machine and Windows 7 (64bit) as host machine,
solved my ploblem; by installing ```vagrant plugin install vagrant-vbguest```.
- I'm using VirtualBox 4.3.26 / vagrant 1.7.2

**Comment by richardasaurus** [comment]
My fix for this was to relocate a folder sync i had configured to sync to `/opt/` on the VM, which then wouldn't allow guest additions to live there.

**Comment by josephbhunt** [comment]
I've tried the fixes mentioned above an none of them work. The error message when running vagrant up said to "(Look at /var/log/vboxadd-install.log to find out what went wrong)". Here's what it said.

```
Creating user for the Guest Additions.
Creating udev rule for the Guest Additions kernel module.
/tmp/vbox.0/Makefile.include.header:97: *** Error: unable to find the sources of your current Linux kernel. Specify KERN_DIR=<directory> and run Make again.  Stop.
```
I'm not sure what to do from here. I'll try upgrading vagrant.

**Comment by er-net** [comment]
I'm trying to create a 'chef/centos-7.0' machine using the "vagrant-vbguest" plugin, and I get an error telling me to look at
```
/var/log/vboxadd-install.log
```

and there I see this error:
```
/tmp/vbox.0/Makefile.include.header:115: *** Error: unable to find the include directory for your current Linux kernel. Specify KERN_INCL=<directory> and run Make again.  Stop.
```

Im running: 
Windows 7
Virtual Box 4.3.28
Vagrant 1.7.2

**Comment by hjianhao** [comment]
I had fixed the problem.
for centos 7 guest os, step by step
1. sudo yum update
2. sudo yum install gcc
3. sudo yum install kernel-devel
4. reboot guest os
5. sudo /etc/init.d/vboxadd setup
6. exit guest os and vagrant reload

for ubuntu 14.04 guest os, step by step
1. install kernel headers : sudo apt-get install linux-headers-`uname -r`
2. download VBoxGuestAdditions_<version>.iso from http://dlc.sun.com.edgesuite.net/virtualbox/<version>, then transfer to you guest os.
3. login to the guest os, mount the ISO : sudo mount VBoxGuestAdditions_<version>.iso /mnt
4. enter the /mnt, and run : sudo ./VBoxLinuxAdditions.run to intall the addtions.
5. exit guest os and vagrant reload

**Comment by pruthvis** [comment]
@hjianhao :+1: your solution fixed the issue for centos 7. Thanks!

**Comment by budhrg** [comment]
I my case my GuestAddition version in my guest was `4.3.10` but I was using VirtualBox version `4.3.26`. 
I have Ubuntu 14.04 (64bit) as both host and guest machine.
I solved my ploblem by installing
 
    vagrant plugin install vagrant-vbguest.

My vagrant version is `vagrant 1.7.2`.

**Comment by umumpaul** [comment]
@hijarian it works. thanks

**Comment by towens** [comment]
@hjianhao :+1: Thanks! worked great for us on centos 7 as well

**Comment by xinyuliu-glu** [comment]
@hijarian Your solution works! Many Thanks.

**Comment by WangWenchao** [comment]
on guest 
```
/etc/init.d/vboxadd setup
```
fix the problem

**Comment by ltutar** [comment]
I have CentOS 6.7 as guest machine and OSX Yosemite as host machine, installing
vagrant plugin install vagrant-vbguest solved my problem
The plug-in took care of the following:
GuestAdditions versions on your host (5.0.4) and guest (4.3.20) do not match.
Installing Virtualbox Guest Additions 5.0.4 - guest version is 4.3.20

**Comment by the-teacher** [comment]
This recipe helped me with Vagrant and Debian 8.1

```sh
vagrant ssh
```

```sh
cd /tmp/
wget http://download.virtualbox.org/virtualbox/5.0.4/VBoxGuestAdditions_5.0.4.iso
sudo mount -o loop VBoxGuestAdditions_5.0.4.iso /mnt
sudo /mnt/VBoxLinuxAdditions.run 
exit
```
```sh
vagrant reload
```

**Comment by isaacperaza** [comment]
Simple and Quick Solution for Failed to mount folders in Linux guest issue.

Add the following line to your Homestead/Vagrantfile:
```
config.vbguest.auto_update = false
```
Your Homestead/Vagrantfile should looks like this:
```
/...

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    
   # To avoid install and uninstall VBoxGuessAdditions during vagrant provisioning.
    config.vbguest.auto_update = false

.../
```

**Comment by RoberMac** [comment]
@hijarian @isaacperaza :+1:

**Comment by langdead** [comment]
Hi, 
do we have any plan to support shared folder for host win7/win8, please?
thx!

**Comment by msandim** [comment]
I'm having issues with the last version of Virtualbox (5.0.8), even with the plugin in vagrant to update the VBoxGuestAdditions automatically.

**Comment by ltutar** [comment]
with the early version installing the  vagrant-vbguest solved my problem. see above. with newer versions I had to uninstall the plugin to get it working again.

**Comment by slave2anubis** [comment]
I have the same issue, i tried all the sugestions from this thread but still no luck.

**Comment by skorp** [comment]
@hjianhao :+1:

**Comment by an0nh4x0r** [comment]
@slave2anubis ... i made solution in a blogpost here http://hackencode.blogspot.com/2015/11/solution-vagrant-cant-mount-shared.html

**Comment by msandim** [comment]
I solved by problem: the problem was having a folder in a path with special characters (e.g. "º"). After I moved the folder where I was going 'vagrant up', everything worked right.

**Comment by alexch** [comment]
FWIW, this just happened to me using these versions:
```
Vagrant 1.7.4
VirtualBox 5.0.10
Guest Additions 5.0.10
ubuntu/trusty64 v20151208.1.0
```
It happened after I ran `vagrant box update` (which might be a red herring) but after trying all sorts of fixes (like adding `vboxsf` to `/etc/modules`, rebuilding the additions manually instead of relying on the `vbguest` plugin, relinking `/usr/lib/VBoxGuestAdditions`, etc.), what worked for me was `vagrant destroy; vagrant init`. Which meant I had to rebuild my guest system, but at least mounting the host dir works again.

**Comment by DanielAron** [comment]
@budhrg :+1:

**Comment by the-teacher** [comment]
xo xo xo. Stop working and Happy New Year!

**Comment by adolphlwq** [comment]
Hi,I run into this problem too.I use another box and solve it.So I recommend box from [https://atlas.hashicorp.com](https://atlas.hashicorp.com/ubuntu/boxes/trusty64)

**Comment by unfulvio** [comment]
this issue is still occurring with Vagrant 1.8 and Virtualbox 5.0.14 - tried the symlink suggestion mentioned several times in this thread as well as using vbguest plugin, to no avail...

**Comment by TheMetalCode** [comment]
I'm experiencing this today with Vagrant 1.8.1 and Virtualbox 5.0.14, right out of the blue. No solution listed here has helped so far.

**Comment by unfulvio** [comment]
hey found out that the issue for me was the number of shared folders

I was working at a setup with over 70 mounted folders - this will trigger that error with Vagrant 4 or 5 if you use vagrant FS - I switched to NFS and the problem solved

it was hard to pin down since the error wasn't pointing in this direction

**Comment by towens** [comment]
The important lines that consistently for us...  
In the Vagrantfile
```
config.vm.provision "shell", path: "cloud_init.sh"
config.vbguest.auto_update = false
```
In the shell provisioning script
```
yum update -y
yum install -y kernel-devel.x86_64
```
Back to the Vagrantfile
`config.vbguest.auto_update = true` then `vagrant reload`
Which should get your geust additions on track. Then, one more time
`config.vbguest.auto_update = false` then `vagrant reload`  

As mentioned :point_up: having the kernel development headers installed  **before** anything else is the trick. Installing the guest additions and syncing folders after has been working on CentOS 6.6 - 7.1.

**Comment by TheMetalCode** [comment]
In my case it was exactly the number of folders being synced. Thanks @unfulvio!

**Comment by creamdog** [comment]
Encountered this problem with Windows 7, Vagrant 1.8.1 and Virtualbox 5.0.14 and launching Ubuntu/Trusty64

Fixed when updating to Virtualbox 5.0.16

**Comment by Voltol** [comment]
I'm getting this, tried so many solutions. 

mesg: ttyname failed: Inappropriate ioctl for device

Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group www-data | cut -d: -f3`,dmode=775, fmode=664 vagrant-B05032-Magento-Box /vagrant-B05032-Magento-Box
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g www-data`,dmode=775, fmode=664 vagrant-B05032-Magento-Box /vagrant-B05032-Magento-Box

vagrant vbguest --status 

GuestAdditions versions on your host (5.0.16) and guest (5.0.17) do not match.

I did 

sudo ln -s /opt/VBoxGuestAdditions-5.0.17/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions

I replaced VBoxGuestAdditions.iso in tmp

Copy iso file C:\Program Files/Oracle/VirtualBox/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso

Still unsolved. 
Somebody has solution, plz?

**Comment by gkollengode** [comment]
Tried all the fixes and none of them worked. This is what has worked for me  finally

CentOS release 6.7 box
```
vagrant ssh
wget  ftp://ftp.pbone.net/mirror/dl.central.org/dl/linuxdev/centos6/x86_64/kernel-devel-2.6.32-431.3.1.el6.x86_64.rpm
sudo yum install kernel-devel-2.6.32-431.3.1.el6.x86_64.rpm -y
wget http://download.virtualbox.org/virtualbox/5.0.4/VBoxGuestAdditions_5.0.4.iso
sudo mount -o loop VBoxGuestAdditions_5.0.4.iso /mnt
sudo /mnt/VBoxLinuxAdditions.run

```
logout and 
vagrant reload


Hope this helps

**Comment by abgaryanharutyun** [comment]
@Voltol  +1

**Comment by gordienkotolik** [comment]
@Voltol same on VirtualBox-5.0.18 and vagrant_1.8.1, 

`
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

PASSWORDHIDDENmPASSWORDHIDDENoPASSWORDHIDDENuPASSWORDHIDDENnPASSWORDHIDDENtPASSWORDHIDDEN PASSWORDHIDDEN-PASSWORDHIDDENtPASSWORDHIDDEN PASSWORDHIDDENcPASSWORDH.........

The error output from the last command was:

stdin: is not a tty
mount error(95): Operation not supported
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

>vagrant vbguest --status
GuestAdditions 5.0.18 running --- OK.
`

**Comment by czerasz** [comment]
I had issues mounting the `/vagrant` directory while using the `vagrant-cachier` plugin.
See more details [here](https://github.com/fgrehm/vagrant-cachier/issues/166#issuecomment-221617147).

Host system: Ubuntu `16.04`
Guest system: Ubuntu `14.04.3`

**Comment by bickerstoff** [comment]
My setup is roughly LAMP stack with centos 6.4 from puphpet.com; I can give more details if it is desired. My error was similar to the initial post @wsouto made although it revolved around the user not existing.

Here is my error message:
```
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

mount -t vboxsf -o uid=`id -u www-data`,gid=`getent group www-data | cut -d: -f3`,dmode=775,fmode=774 vflsf_092515h4p5zx /var/www/html
mount -t vboxsf -o uid=`id -u www-data`,gid=`id -g www-data`,dmode=775,fmode=774 vflsf_092515h4p5zx /var/www/html

The error output from the last command was:

id: www-data: No such user
id: www-data: No such user
uid= requires an argument (i.e. uid==<arg>)
```


I changed the user to vagrant and the group to vagrant as I knew those would exist and was able to pass this issue. (Under synced_folder in config.yaml if you are using puphpet.com's setup)

**Comment by exrajeev** [comment]
Thanks hjianhao  . Your solution worked out for me

**Comment by hao203** [comment]
very good

**Comment by christianbueno1** [comment]
I had the same  problem in VirtualBox 5.1.16
My Os: Windows 10
vagrant version: 1.9.2
box: ubuntu/trusty32
I am working with a vagrant file provide by Udacity , in the course "Intro to Relational Databases".
I fixed that problem, uninstalling VirtualBox 5.1.16 and then install VirtualBox 5.1.14
---
vagrant-vbguest did not work for me and neither the command
`$ sudo ln -s /opt/VBoxGuestAdditions-4.3.10/lib/VBoxGuestAdditions /usr/lib/VBoxGuestAdditions`

**Comment by szeitlin** [comment]
Same problem on VirtualBox 5.1.10
Vagrant 1.9.1
box: Ubuntu 14.04.5
OS: Mac 10.12.3 (Sierra)

**Comment by claudiobizzotto** [comment]
Happened to me with version `5.1.20`. Here's how I fixed it: [gist](https://gist.github.com/claudiobizzotto/67dfcf66ebffca58b1075123c2e898f8)

**Comment by Jalle19** [comment]
The Linux guest additions in VirtualBox 5.1.20 are indeed broken, see https://www.virtualbox.org/ticket/16670. I reverted to 5.1.18 to get work done.

**Comment by lokeoke** [comment]
Had the same issue with VirtualBox 5.1.20. Now issue is fixed in VirtualBox 5.1.22 release.

**Comment by osmanddas** [comment]
As mentioned above, I got the issue resolved by installing vagrant-vbguest ($ vagrant plugin install vagrant-vbguest). Thanks a lot for sharing the solution. 

FYI - I didn't face this issue until I had to use multiple vagrant boxes with a shared directory. Never faced it till I was using one virtual box at a time.

**Comment by Alexandre1202** [comment]
The uninstall of vagrant does not delete %HOME_DIR%\.vagrant.d but before install other version it is important you do it manually.
I also remove unused directories inside of %HOME_DIR%\VirtualBox VMs and %HOME_DIR%\.VirtualBox

**Comment by wzurrr** [comment]
Me on Windows running VirtualBox 5.2.6 and Vagrant 2.0.1

When trying to sync a folder, got the vboxsf error message. After performing "vagrant plugin install vagrant-vbguest" on the host the "vagrant up" command caused the VMs to boot nicely. They seem to be able to use the guest additions, building a VirtualBox Guest Additions kernel module.

**Comment by tlvu** [comment]
Still happen on VirtualBox 6.0.8 on Linux Ubuntu 18.04.  Downgrade the VBoxGuestAdditions to 5.2.18 in my Ubuntu 18.04 VM works against my VirtualBox 6.0.8 host.  Followed this gist for downgrade.
