### ISSUE TITLE
Plugin install behind corparate firewall fails

### ISSUE THREAD

**Issue by joerg** [hashicorp/vagrant#8897]
Hi,

I am trying to install a plugin on one of my servers which is behind a corporate firewall without any Internet access. But I do have an Artifactory instance which does have access to the Internet and I did create a remote repo for https://gems.hashicorp.com/ there. So accessing https://rcrs.rbinternational.com/artifactory/api/gems/gems/ will include rubygems.org and gems.hashicorp.com.

### Vagrant version
1.9.7

### Host operating system
RHEL 7.3

### Debug output
https://gist.github.com/joerg/d171807c4af99d05bde641c438a91ba1

Plus I get this error in my Artifactory logs
`org.artifactory.request.RemoteRequestException: Error fetching https://gems.hashicorp.com/prerelease_specs.4.8.gz (remote response: 403: Forbidden)`

### Expected behavior
Plugin should be installed.

### Actual behavior
```
 Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-share (> 0)'
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

Unable to resolve dependency: user requested 'vagrant-share (> 0)'
```

### Steps to reproduce
1. Install and set up artifactory with a rubygems repository.
2. Add the repository for gems.hashicorp.com as a remote gem repository and add this remote to the gems virtual repository.
3. Install the plugin using the dedicated artifactory mirror.

**Comment by jamesryan1** [comment]
Please can you try running a --plugin-clean-sources?

https://www.vagrantup.com/docs/cli/plugin.html#plugin-clean-sources

"Clears all sources that have been defined so far. This is an advanced feature. The use case is primarily for corporate firewalls that prevent access to RubyGems.org."

**Comment by joerg** [comment]
Please check the debug output I already posted which clearly shows in the first line that I did run the plugin install with this option.

**Comment by chrisroberts** [comment]
I believe if you pull the vagrant-share gem from the hashicorp gem repository and include it within your custom repository that should resolve the solution generation error you are encountering.

**Comment by joerg** [comment]
Hi,
Our local gem repository is merely a proxy (check the JFrog Artifactory docs if you want to know more) to the hashicorp repo. I can not manually funnel around in there.

**Comment by zambien** [comment]
I am seeing the same issue as @joerg.  There doesn't seem to be a way to get vagrant-share included into our Artifactory mirror.

**Comment by chrisroberts** [comment]
The vagrant-share plugin has been removed from the install packages. If the plugin still exists when listing installed plugins (`vagrant plugin list`) simply removing the plugin (`vagrant plugin uninstall vagrant-share`) will resolve the issue.

Cheers!

**Comment by gena01** [comment]
I am seeing the same issue with latest vagrant 2.2.x. Tried passing both --plugin-clean-sources --plugin-source

Looks like something regressed since I am still seeing this in the debug log:
```log
DEBUG bundler: Enabling user defined remote RubyGems sources
DEBUG bundler: Adding RubyGems source http://artifactory.xxxxxxxx/artifactory/api/gems/ruby-repos/
DEBUG bundler: Enabling default remote RubyGems sources
DEBUG bundler: Adding source - https://gems.hashicorp.com/
DEBUG bundler: Adding source - https://rubygems.org/
```
